# Workflow name, visible on GitHub UI.
name: release

# Run the workflow when a commit is pushed to a version tag
on:
  push:
    tags:
      - '*.*.*'

# List of jobs that will be run concurrently
jobs:
  # Name of the job
  build:

    # Platform GitHub will use to run workflow, we pick Windows for no particular reason
    runs-on: ubuntu-latest

    # Make sure Arduino CLI allows to install libraries with --git-url
    env:
          ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true

    # List of steps this job will run
    steps:

      # Clone the repo using the `checkout` action
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platforio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Install the platform and dependencies
      - name: Build PlatformIO Project
        run: pio run

      # Create a release with binary file
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/d1_mini/firmware.bin