# Workflow name, visible on GitHub UI.
name: test

# Run the workflow when a commit is pushed or a Pull Request is opened
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:

# List of jobs that will be run concurrently
jobs:
  # Name of the job
  test:
    # Based on example in platformio docs
    runs-on: ubuntu-latest

    # List of steps this job will run
    steps:

      # Clone the repo using the `checkout` action
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platforio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Install the platform and dependencies
      - name: Build PlatformIO Project
        run: pio run
      
      # Upload binary files as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: .pio/build/d1_mini/firmware.bin
